--1.IN THE GIVEN DATASET,WHO HAVE ORDERED THE PRODUCTS THE MOST
--MALE/FEMALE?
SELECT GENDER,COUNT(*) TOTAL_ORDERS
FROM STORE
GROUP BY GENDER;
--FROM THE ABOVE QUERRY WE CAN SEE THAT MOST OF THE BUYERS ARE FEMALE  



--2.WHO HAS THE MOST  PURCHASING POWER OF FEMALE OR MALE.
SELECT GENDER,SUM(AMOUNT) AS TOTAL_SUM
FROM STORE
GROUP BY GENDER;


--3.HOW MUCH ORDERS HAS GENERATED FROM ADULT,TEENAGER,SENIOR WOMEN
SELECT GENDER,AGE_GROUP,COUNT(*) AS TOTAL_COUNT
FROM STORE
WHERE UPPER(GENDER)='WOMEN' 
GROUP BY GENDER,AGE_GROUP
ORDER BY TOTAL_COUNT DESC;

--3.HOW MUCH Profit HAS GENERATED FROM ADULT,TEENAGER,SENIOR WOMEN?