--Write a query to display-
--IN THE GIVEN DATASET,WHO HAVE ORDERED THE PRODUCTS THE MOST
--MALE/FEMALE?
SELECT GENDER,COUNT(*) TOTAL_ORDERS
FROM STORE
GROUP BY GENDER;

--FROM THE ABOVE QUERRY WE CAN SEE THAT MOST OF THE BUYERS ARE FEMALE AND EVEN 



--2.WHO HAS THE MOST  PURCHASING POWER OF FEMALE IS MORE THAN MALE.

SELECT GENDER,SUM(AMOUNT) AS TOTAL_SUM
FROM STORE
GROUP BY GENDER;