SELECT *
FROM STORE;

--01.CREATE A MATERIALIZED VIEW AND DISPLAY WHICH STATE HAS MAXIMUM PUSRCHASE POWER

CREATE  MATERIALIZED VIEW MV1_STORE
AS
SELECT 
SHIP_STATE,GENDER,MAX(AMOUNT) AS MAXIMUM_AMOUNT
FROM STORE
GROUP BY SHIP_STATE,GENDER
ORDER BY MAX(AMOUNT);

SELECT *
FROM MV1_STORE;
GRANT SELECT ON mv1_store TO STORE_CLIENT;

--HOW TO REFRESH THE MATERIALIZED VIEW ,IF ANY CHANGES MADE IN QUERRY OR NEW DATA ADDED.
EXEC DBMS_MVIEW.REFRESH('MV1_STORE', 'C');

--TO CHECK THE MATERAILIZED VIEW STATUS REFRESH OR NOT
SELECT MVIEW_NAME, STALENESS
FROM USER_MVIEWS
WHERE MVIEW_NAME = 'MV1_STORE';

