SELECT *
FROM STORE;

--01.CREATE A MATERIALIZED VIEW AND DISPLAY WHICH STATE HAS MAXIMUM PUSRCHASE POWER
CREATE  MATERIALIZED VIEW MV1_STORE
AS
SELECT 
SHIP_STATE,GENDER,MAX(AMOUNT) AS MAXIMUM_AMOUNT
FROM STORE
GROUP BY SHIP_STATE,GENDER
ORDER BY MAX(AMOUNT);

SELECT *
FROM MV1_STORE;
GRANT SELECT ON mv1_store TO STORE_CLIENT;

--HOW TO REFRESH THE MATERIALIZED VIEW ,IF ANY CHANGES MADE IN QUERRY OR NEW DATA ADDED.
EXEC DBMS_MVIEW.REFRESH('MV1_STORE', 'C');

--TO CHECK THE MATERAILIZED VIEW STATUS REFRESH OR NOT
SELECT MVIEW_NAME, STALENESS
FROM USER_MVIEWS
WHERE MVIEW_NAME = 'MV1_STORE';




--============================================================================
--01.CREATE MATERIALIZED VIEW TO GET DETAILS 
--WHICH STATE  HAS GENERATED LOWEST PROFIT 
SELECT *
FROM STORE;

SELECT SHIP_STATE, SUM(AMOUNT) AS TOTAL_PROFIT
FROM STORE
GROUP BY SHIP_STATE
ORDER BY TOTAL_PROFIT ASC;



--============================================================================
--WHICH ITEMS IN MAHARASHTRA ARE TOP SELLING

CREATE MATERIALIZED VIEW MAHA_PRO_TOP_SELL
AS
SELECT SHIP_STATE,CATEGORY,COUNT(*) AS TOTAL_COUNT,SUM(AMOUNT) AS TOTAL_SUM
FROM STORE
WHERE UPPER(SHIP_STATE)='MAHARASHTRA'
GROUP BY CATEGORY,SHIP_STATE
ORDER BY TOTAL_COUNT DESC;

GRANT SELECT ON MAHA_PRO_TOP_SELL TO STORE_CLIENT;


--HOW TO REFRESH THE MATERIALIZED VIEW ,IF ANY CHANGES MADE IN QUERRY OR NEW DATA ADDED.
EXEC DBMS_MVIEW.REFRESH('MAHA_PRO_TOP_SELL', 'C');

--TO CHECK THE MATERAILIZED VIEW STATUS REFRESH OR NOT
SELECT MVIEW_NAME, STALENESS
FROM USER_MVIEWS
WHERE MVIEW_NAME = 'MAHA_PRO_TOP_SELL';


--HOW TO UPDATED MATERIALIZED VIEW


