SELECT *
FROM STORE;

--01.CREATE A VIEW AND DISPLAY WHICH STATE HAS MAXIMUM PUSRCHASE POWER
CREATE OR REPLACE VIEW STORE_VIEW1
AS
SELECT SHIP_STATE,MAX(AMOUNT) AS MAXIMUM_AMOUNT 
FROM STORE
GROUP BY SHIP_STATE
ORDER BY MAXIMUM_AMOUNT DESC;

SELECT *
FROM STORE_VIEW1;

CREATE USER STORE_CLIENT IDENTIFIED BY root;
GRANT CREATE SESSION TO STORE_CLIENT;
GRANT SELECT ON STORE_VIEW1 TO STORE_CLIENT;
