SELECT *
FROM STORE;

--01.CREATE A VIEW AND DISPLAY WHICH STATE HAS MAXIMUM PUSRCHASE POWER
CREATE OR REPLACE VIEW STORE_VIEW1
AS
SELECT SHIP_STATE,MAX(AMOUNT) AS MAXIMUM_AMOUNT 
FROM STORE
GROUP BY SHIP_STATE
ORDER BY MAXIMUM_AMOUNT DESC;

SELECT *
FROM STORE_VIEW1;

CREATE USER STORE_CLIENT IDENTIFIED BY root;
GRANT CREATE SESSION TO STORE_CLIENT;
GRANT SELECT ON STORE_VIEW1 TO STORE_CLIENT;

--2.CREATE A VIEW TO DISPLAY WHICH AGE_GROUP HAVE PURCHASED A LOT
CREATE OR REPLACE VIEW STORE_VIEW2
AS
SELECT AGE_GROUP,SUM(AMOUNT) AS PURCHASE_POWER
FROM STORE
GROUP BY AGE_GROUP
ORDER BY PURCHASE_POWER DESC;

SELECT *
FROM STORE_VIEW2;
GRANT SELECT ON STORE_VIEW2 TO STORE_CLIENT;

--03.CREATE VIEW ON FOLLOWING ,GRANT ACCESS TO STORE_CLIENT
--   Get the total number of orders and the sum of amounts for each status:
CREATE OR REPLACE VIEW CHECK_STATUS_AMOUNT_VIEW
AS
SELECT STATUS,COUNT(ORDER_ID)AS TOTAL_COUNT,SUM(AMOUNT) AS TOTAL_SUM
FROM STORE
GROUP BY STATUS
ORDER BY TOTAL_SUM DESC;
GRANT SELECT ON CHECK_STATUS_AMOUNT_VIEW TO STORE_CLIENT;

--04.CREATE A VIEW 
--Find the average age of customers by gender:GRANT ACCESS TO STORE_CLIENT
CREATE OR REPLACE VIEW AVG_AGE_VIEW
AS
SELECT GENDER, TRUNC(AVG(AGE)) AS AVEGARGE_AGE
FROM STORE
GROUP BY GENDER;
GRANT SELECT ON AVG_AGE_VIEW TO STORE_CLIENT; 

--CREATE A VIEW TO FIND
--Total Sales by Month and Status:
CREATE OR REPLACE VIEW TOTAL_SALE_BY_MONTH_VIEW
AS
SELECT MONTH, STATUS,SUM(AMOUNT) AS TOTAL_SALE
FROM STORE
GROUP BY MONTH,STATUS
ORDER BY MONTH;
GRANT SELECT ON TOTAL_SALE_BY_MONTH_VIEW TO STORE_CLIENT;

--CREATE A VIEW TO IDENTIFY TOP SELLING PRODUCT IN STORE
CREATE OR REPLACE VIEW TOP_SELLING_PRODCT_VIEW
AS
SELECT CATEGORY, SUM(AMOUNT) AS TOTAL_AMOUNT
FROM STORE
GROUP BY CATEGORY
ORDER BY TOTAL_AMOUNT DESC;
GRANT SELECT ON TOP_SELLING_PRODCT_VIEW TO STORE_CLIENT;

--TOP PROFIT GENERATED FROM WHICH CITY
CREATE OR REPLACE VIEW TOP_PROFITABLE_CITIES_VIEW
AS
SELECT SHIP_CITY,SUM(AMOUNT)AS TOTAL_AMOUNT
FROM STORE
GROUP BY SHIP_CITY
ORDER BY TOTAL_AMOUNT DESC;

GRANT SELECT ON TOP_PROFITABLE_CITIES_VIEW TO STORE_CLIENT;