SELECT *
FROM STORE;

--EXTRACT THE MAX PROFIT  IN EACH CATEGORY
SELECT CATEGORY ,SUM(AMOUNT) AS MAXI
FROM STORE
GROUP BY CATEGORY;

----Q1.. Write a query to display top 3 AMOUNT 
SELECT *
FROM (
SELECT ORDER_NUMBER, ORDER_ID,CUST_ID, AMOUNT,
DENSE_RANK() OVER (ORDER BY AMOUNT DESC ) AS RNK
FROM STORE) TEMP_01
WHERE TEMP_01.RNK <= 3;

----Q1.. Write a query to display BOTTOM 3 AMOUNT  
SELECT *
FROM (
SELECT ORDER_NUMBER, ORDER_ID,CUST_ID, AMOUNT,
DENSE_RANK() OVER (ORDER BY AMOUNT ASC ) AS RNK
FROM STORE) TEMP_01
WHERE TEMP_01.RNK <= 3;


--lead
select ORDER_NUMBER,CATEGORY,lead(AMOUNT) over (order by AMOUNT)as  new_AMT
from STORE;
--lead with offset default value
select ORDER_NUMBER,CATEGORY,lead(AMOUNT,1,0) over (order by AMOUNT)as  new_AMT
from STORE;

