SELECT *
FROM STORE;

--EXTRACT THE MAX PROFIT  IN EACH CATEGORY
SELECT CATEGORY ,SUM(AMOUNT) AS MAXI
FROM STORE
GROUP BY CATEGORY;

--Extract top 3 STATE  BY AMOUNT AMOUNT
SELECT *FROM(
SELECT SHIP_STATE,AMOUNT,
DENSE_RANK() OVER(ORDER BY AMOUNT DESC) AS DEN
FROM STORE
)WHERE DEN<4;

--03.WRITE A QUERY TO LIST OUT ALL DUPLICATE RECORDS FROM A TABLE
SELECT ORDER_NUMBER ,COUNT(*) AS CNT
FROM STORE
GROUP BY ORDER_NUMBER
HAVING COUNT(*)>1;

--04.WRITE A QUERY TO DISPLAY TOP 3 AMOUNT Generating state and city.
SELECT *FROM(
SELECT SHIP_STATE,SHIP_CITY,AMOUNT,
DENSE_RANK() OVER(ORDER BY AMOUNT DESC) AS DEN
FROM STORE
)WHERE DEN<4;

--06.WRITE A QUERY TO DISPLAY BOTTOM 3 Amount Generating state and city
--07.WRITE A QUERY TO DISPLAY State WISE TOP 3 Amount
SELECT SHIP_STATE,SHIP_CITY,AMOUNT,
DENSE_RANK()  OVER(PARTITION BY SHIP_STATE ORDER BY AMOUNT DESC) AS DEN
FROM STORE
ORDER BY AMOUNT DESC;




SELECT *
FROM STORE;


SELECT SHIP_STATE,SHIP_CITY,AMOUNT,
DENSE_RANK() OVER(ORDER BY AMOUNT DESC) AS DEN
FROM STORE;