--Explain with caluse with querry


    --sum amount avg amount
  SELECT * FROM STORE;  
WITH TEMP_01 
AS
(
SELECT CATEGORY, TRUNC(AVG(AMOUNT)) AS AVG_AMT
FROM STORE
GROUP BY CATEGORY
) ,
TEMP_02
AS
( SELECT CATEGORY,SUM(AMOUNT) AS SUM_AMT
FROM STORE
GROUP BY CATEGORY
)

SELECT t1.CATEGORY , t1.AVG_AMT ,t2.SUM_AMT
FROM TEMP_01 t1 JOIN TEMP_02 t2
ON(t1.CATEGORY = t2.CATEGORY
AND t1.AVG_AMT < t2.SUM_AMT);